# Generated by Django 4.1.5 on 2023-05-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('teg', models.TextField(blank=True)),
                ('images', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('content', models.TextField(blank=True)),
                ('grade_num', models.IntegerField()),
                ('language', models.CharField(max_length=255)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
